<?xml version="1.0" encoding="utf-8"?><Database Name="ContactsBook" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=VI-PC\SQLEXPRESS;Initial Catalog=ContactsBook;Integrated Security=True;Encrypt=False;TrustServerCertificate=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="ContactsBookConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Contact" Member="ContactDBs">
    <Type Name="ContactDB">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="Surname" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="Age" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="GroupId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="Note" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Association Name="Group_Contact" Member="GroupDB" ThisKey="GroupId" OtherKey="Id" Type="GroupDB" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.[Group]" Member="GroupDBs">
    <Type Name="GroupDB">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Association Name="Group_Contact" Member="ContactDBs" ThisKey="Id" OtherKey="GroupId" Type="ContactDB" />
    </Type>
  </Table>
</Database>